version: "3.9"

services:
  event:
    build: ./Event
    image: event
    container_name: eventContainer
    ports:
      - "8099:8099"
    depends_on:
      - db-mysql
      - eureka
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/Event?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=@ziz3101
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    networks:
      - my-network
  ticket:
    build: ./Ticket
    image: ticket
    container_name: ticketContainer
    ports:
      - "8098:8098"
    depends_on:
      - db-mysql
      - eureka
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/Ticket?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=@ziz3101
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    networks:
      - my-network
  exercice:
    build: ./Exercice
    image: exercice
    container_name: exerciceContainer
    ports:
      - "8088:8088"
    depends_on:
      - eureka
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    networks:
      - my-network
  programme:
    build: ./Programme
    image: programme
    container_name: programmeContainer
    ports:
      - "8089:8089"
    depends_on:
      - eureka
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    networks:
      - my-network
  food:
    build: ./Food
    image: food
    container_name: foodContainer
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    networks:
      - my-network
  ingredient:
    build: ./Ingredient
    image: ingredient
    container_name: ingredientContainer
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    networks:
      - my-network
  actuality:
    build: ./Actuality
    image: actuality
    container_name: actualityContainer
    ports:
      - "8086:8086"
    depends_on:
      - db-mysql
      - eureka
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/Actuality?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=@ziz3101
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    networks:
      - my-network
  commentaire:
    build: ./Commentaire
    image: commentaire
    container_name: commentaireContainer
    ports:
      - "8085:8085"
    depends_on:
      - db-mysql
      - eureka
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/Commentaire?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=@ziz3101
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    networks:
      - my-network
  product:
    build: ./Product
    image: product
    container_name: productContainer
    ports:
      - "8008:8008"
    depends_on:
      - eureka
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    networks:
      - my-network
  cart:
    build: ./Cart
    image: cart
    container_name: cartContainer
    ports:
      - "8009:8009"
    depends_on:
      - eureka
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    networks:
      - my-network
  db-mysql:
    image: "mysql:8.0"
    container_name: db-mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=@ziz3101
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network
  gateway:
    build: ./gateway
    image: gateway
    container_name: gatewayContainer
    ports:
      - "8093:8093"
    depends_on:
      - eureka
      - event
      - ticket
      - programme
      - exercice
      - actuality
      - commentaire
      - food
      - ingredient
      - product
      - cart
      - keycloak
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/healthfit
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/healthfit/protocol/openid-connect/certs
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    networks:
      - my-network
  eureka:
    build: ./Eureka
    image: eureka
    container_name: eurekaContainer
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8761/eureka/
    networks:
      - my-network
  config-server:
    build: ./ConfigServer
    image: configserver
    container_name: configserverContainer
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - my-network
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloakContainer
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=adminAWD
      - KEYCLOAK_ADMIN_PASSWORD=adminAWD
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://db-mysql:3306/keycloakdb?createDatabaseIfNotExist=true
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=@ziz3101
    command: start-dev
    depends_on:
      - db-mysql
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/realms/healthfit/protocol/openid-connect/certs" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - my-network
volumes:
  mysql-data:
    driver: local
  keycloak-data:
    driver: local
networks:
  my-network:
    driver: bridge