spring:
  application:
    name: GATEWAY
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
      routes:
        - id: Food
          uri: lb://Food
          predicates:
            - Path=/foods/**
        - id: Ingredient
          uri: lb://Ingredient
          predicates:
            - Path=/ingredients/**
        - id: Event
          uri: lb://Event
          predicates:
            - Path=/Event/event/**
        - id: Ticket
          uri: lb://Ticket
          predicates:
            - Path=/Ticket/ticket/**
        - id: Exercice
          uri: lb://Exercice
          predicates:
            - Path=/exercice/**
        - id: Programme
          uri: lb://Programme
          predicates:
            - Path=/programme/**
        - id: Commentaire
          uri: lb://Commentaire
          predicates:
            - Path=/api/comments/**
        - id: Actuality
          uri: lb://ACTUALITY
          predicates:
            - Path=/api/actualities/**

        - id: Product
          uri: lb://Product
          predicates:
            - Path=/product/**
        - id: Cart
          uri: lb://Cart
          predicates:
            - Path=/cart/**


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/AWD-Realm
          jwk-set-uri: http://localhost:8080/realms/AWD-Realm/protocol/openid-connect/certs

server:
  port: 8093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
