spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: Ingredient
          uri: http://localhost:8082
          predicates:
            - Path=/ingredients/**
        - id: Food
          uri: http://localhost:8081
          predicates:
            - Path=/foods/**
    loadbalancer:
      enabled: true

server:
  port: 8093

# Eureka registration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
